/*
 * Copyright (C) Copyright 2014 Glencoe Software, Inc. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */


#include <omero/client.h>
#include <omero/RTypesI.h>
#include <Ice/Handle.h>
#include <omero/api/Gateway.h>
#include <omero/api/IAdmin.h>
#include <omero/api/IContainer.h>
#include <omero/api/IMetadata.h>
#include <omero/api/IQuery.h>
#include <omero/api/IPixels.h>
#include <omero/api/ITypes.h>
#include <omero/api/IUpdate.h>
#include <omero/api/RawPixelsStore.h>
#include <omero/api/RawFileStore.h>
#include <omero/sys/ParametersI.h>
#include <omero/model/AcquisitionMode.h>
#include <omero/model/AcquisitionModeI.h>
#include <omero/model/Annotation.h>
#include <omero/model/AnnotationAnnotationLink.h>
#include <omero/model/AnnotationAnnotationLinkI.h>
#include <omero/model/AnnotationI.h>
#include <omero/model/Arc.h>
#include <omero/model/ArcI.h>
#include <omero/model/ArcType.h>
#include <omero/model/ArcTypeI.h>
#include <omero/model/BasicAnnotation.h>
#include <omero/model/BasicAnnotationI.h>
#include <omero/model/Binning.h>
#include <omero/model/BinningI.h>
#include <omero/model/BooleanAnnotation.h>
#include <omero/model/BooleanAnnotationI.h>
#include <omero/model/Channel.h>
#include <omero/model/ChannelAnnotationLink.h>
#include <omero/model/ChannelAnnotationLinkI.h>
#include <omero/model/ChannelBinding.h>
#include <omero/model/ChannelBindingI.h>
#include <omero/model/ChannelI.h>
#include <omero/model/ChecksumAlgorithm.h>
#include <omero/model/ChecksumAlgorithmI.h>
#include <omero/model/CodomainMapContext.h>
#include <omero/model/CodomainMapContextI.h>
#include <omero/model/CommentAnnotation.h>
#include <omero/model/CommentAnnotationI.h>
#include <omero/model/ContrastMethod.h>
#include <omero/model/ContrastMethodI.h>
#include <omero/model/ContrastStretchingContext.h>
#include <omero/model/ContrastStretchingContextI.h>
#include <omero/model/Correction.h>
#include <omero/model/CorrectionI.h>
#include <omero/model/Dataset.h>
#include <omero/model/DatasetAnnotationLink.h>
#include <omero/model/DatasetAnnotationLinkI.h>
#include <omero/model/DatasetI.h>
#include <omero/model/DatasetImageLink.h>
#include <omero/model/DatasetImageLinkI.h>
#include <omero/model/DBPatch.h>
#include <omero/model/DBPatchI.h>
#include <omero/model/Details.h>
#include <omero/model/DetailsI.h>
#include <omero/model/Detector.h>
#include <omero/model/DetectorI.h>
#include <omero/model/DetectorSettings.h>
#include <omero/model/DetectorSettingsI.h>
#include <omero/model/DetectorType.h>
#include <omero/model/DetectorTypeI.h>
#include <omero/model/Dichroic.h>
#include <omero/model/DichroicI.h>
#include <omero/model/DimensionOrder.h>
#include <omero/model/DimensionOrderI.h>
#include <omero/model/DoubleAnnotation.h>
#include <omero/model/DoubleAnnotationI.h>
#include <omero/model/Ellipse.h>
#include <omero/model/EllipseI.h>
#include <omero/model/Event.h>
#include <omero/model/EventI.h>
#include <omero/model/EventLog.h>
#include <omero/model/EventLogI.h>
#include <omero/model/EventType.h>
#include <omero/model/EventTypeI.h>
#include <omero/model/Experiment.h>
#include <omero/model/Experimenter.h>
#include <omero/model/ExperimenterAnnotationLink.h>
#include <omero/model/ExperimenterAnnotationLinkI.h>
#include <omero/model/ExperimenterGroup.h>
#include <omero/model/ExperimenterGroupAnnotationLink.h>
#include <omero/model/ExperimenterGroupAnnotationLinkI.h>
#include <omero/model/ExperimenterGroupI.h>
#include <omero/model/ExperimenterI.h>
#include <omero/model/ExperimentI.h>
#include <omero/model/ExperimentType.h>
#include <omero/model/ExperimentTypeI.h>
#include <omero/model/ExternalInfo.h>
#include <omero/model/ExternalInfoI.h>
#include <omero/model/Family.h>
#include <omero/model/FamilyI.h>
#include <omero/model/Filament.h>
#include <omero/model/FilamentI.h>
#include <omero/model/FilamentType.h>
#include <omero/model/FilamentTypeI.h>
#include <omero/model/FileAnnotation.h>
#include <omero/model/FileAnnotationI.h>
#include <omero/model/Fileset.h>
#include <omero/model/FilesetAnnotationLink.h>
#include <omero/model/FilesetAnnotationLinkI.h>
#include <omero/model/FilesetEntry.h>
#include <omero/model/FilesetEntryI.h>
#include <omero/model/FilesetI.h>
#include <omero/model/FilesetJobLink.h>
#include <omero/model/FilesetJobLinkI.h>
#include <omero/model/FilesetVersionInfo.h>
#include <omero/model/FilesetVersionInfoI.h>
#include <omero/model/Filter.h>
#include <omero/model/FilterI.h>
#include <omero/model/FilterSet.h>
#include <omero/model/FilterSetEmissionFilterLink.h>
#include <omero/model/FilterSetEmissionFilterLinkI.h>
#include <omero/model/FilterSetExcitationFilterLink.h>
#include <omero/model/FilterSetExcitationFilterLinkI.h>
#include <omero/model/FilterSetI.h>
#include <omero/model/FilterType.h>
#include <omero/model/FilterTypeI.h>
#include <omero/model/Format.h>
#include <omero/model/FormatI.h>
#include <omero/model/GroupExperimenterMap.h>
#include <omero/model/GroupExperimenterMapI.h>
#include <omero/model/Illumination.h>
#include <omero/model/IlluminationI.h>
#include <omero/model/Image.h>
#include <omero/model/ImageAnnotationLink.h>
#include <omero/model/ImageAnnotationLinkI.h>
#include <omero/model/ImageI.h>
#include <omero/model/ImagingEnvironment.h>
#include <omero/model/ImagingEnvironmentI.h>
#include <omero/model/Immersion.h>
#include <omero/model/ImmersionI.h>
#include <omero/model/ImportJob.h>
#include <omero/model/ImportJobI.h>
#include <omero/model/IndexingJob.h>
#include <omero/model/IndexingJobI.h>
#include <omero/model/Instrument.h>
#include <omero/model/InstrumentI.h>
#include <omero/model/IntegrityCheckJob.h>
#include <omero/model/IntegrityCheckJobI.h>
#include <omero/model/IObject.h>
#include <omero/model/Job.h>
#include <omero/model/JobI.h>
#include <omero/model/JobOriginalFileLink.h>
#include <omero/model/JobOriginalFileLinkI.h>
#include <omero/model/JobStatus.h>
#include <omero/model/JobStatusI.h>
#include <omero/model/Label.h>
#include <omero/model/LabelI.h>
#include <omero/model/Laser.h>
#include <omero/model/LaserI.h>
#include <omero/model/LaserMedium.h>
#include <omero/model/LaserMediumI.h>
#include <omero/model/LaserType.h>
#include <omero/model/LaserTypeI.h>
#include <omero/model/LightEmittingDiode.h>
#include <omero/model/LightEmittingDiodeI.h>
#include <omero/model/LightPath.h>
#include <omero/model/LightPathEmissionFilterLink.h>
#include <omero/model/LightPathEmissionFilterLinkI.h>
#include <omero/model/LightPathExcitationFilterLink.h>
#include <omero/model/LightPathExcitationFilterLinkI.h>
#include <omero/model/LightPathI.h>
#include <omero/model/LightSettings.h>
#include <omero/model/LightSettingsI.h>
#include <omero/model/LightSource.h>
#include <omero/model/LightSourceI.h>
#include <omero/model/Line.h>
#include <omero/model/LineI.h>
#include <omero/model/Link.h>
#include <omero/model/LinkI.h>
#include <omero/model/ListAnnotation.h>
#include <omero/model/ListAnnotationI.h>
#include <omero/model/LogicalChannel.h>
#include <omero/model/LogicalChannelI.h>
#include <omero/model/LongAnnotation.h>
#include <omero/model/LongAnnotationI.h>
#include <omero/model/Mask.h>
#include <omero/model/MaskI.h>
#include <omero/model/Medium.h>
#include <omero/model/MediumI.h>
#include <omero/model/MetadataImportJob.h>
#include <omero/model/MetadataImportJobI.h>
#include <omero/model/MicrobeamManipulation.h>
#include <omero/model/MicrobeamManipulationI.h>
#include <omero/model/MicrobeamManipulationType.h>
#include <omero/model/MicrobeamManipulationTypeI.h>
#include <omero/model/Microscope.h>
#include <omero/model/MicroscopeI.h>
#include <omero/model/MicroscopeType.h>
#include <omero/model/MicroscopeTypeI.h>
#include <omero/model/Namespace.h>
#include <omero/model/NamespaceAnnotationLink.h>
#include <omero/model/NamespaceAnnotationLinkI.h>
#include <omero/model/NamespaceI.h>
#include <omero/model/Node.h>
#include <omero/model/NodeAnnotationLink.h>
#include <omero/model/NodeAnnotationLinkI.h>
#include <omero/model/NodeI.h>
#include <omero/model/NumericAnnotation.h>
#include <omero/model/NumericAnnotationI.h>
#include <omero/model/Objective.h>
#include <omero/model/ObjectiveI.h>
#include <omero/model/ObjectiveSettings.h>
#include <omero/model/ObjectiveSettingsI.h>
#include <omero/model/OriginalFile.h>
#include <omero/model/OriginalFileAnnotationLink.h>
#include <omero/model/OriginalFileAnnotationLinkI.h>
#include <omero/model/OriginalFileI.h>
#include <omero/model/OTF.h>
#include <omero/model/OTFI.h>
#include <omero/model/ParseJob.h>
#include <omero/model/ParseJobI.h>
#include <omero/model/Path.h>
#include <omero/model/PathI.h>
#include <omero/model/Permissions.h>
#include <omero/model/PermissionsI.h>
#include <omero/model/PhotometricInterpretation.h>
#include <omero/model/PhotometricInterpretationI.h>
#include <omero/model/PixelDataJob.h>
#include <omero/model/PixelDataJobI.h>
#include <omero/model/Pixels.h>
#include <omero/model/PixelsAnnotationLink.h>
#include <omero/model/PixelsAnnotationLinkI.h>
#include <omero/model/PixelsI.h>
#include <omero/model/PixelsOriginalFileMap.h>
#include <omero/model/PixelsOriginalFileMapI.h>
#include <omero/model/PixelsType.h>
#include <omero/model/PixelsTypeI.h>
#include <omero/model/PlaneInfo.h>
#include <omero/model/PlaneInfoAnnotationLink.h>
#include <omero/model/PlaneInfoAnnotationLinkI.h>
#include <omero/model/PlaneInfoI.h>
#include <omero/model/PlaneSlicingContext.h>
#include <omero/model/PlaneSlicingContextI.h>
#include <omero/model/Plate.h>
#include <omero/model/PlateAcquisition.h>
#include <omero/model/PlateAcquisitionAnnotationLink.h>
#include <omero/model/PlateAcquisitionAnnotationLinkI.h>
#include <omero/model/PlateAcquisitionI.h>
#include <omero/model/PlateAnnotationLink.h>
#include <omero/model/PlateAnnotationLinkI.h>
#include <omero/model/PlateI.h>
#include <omero/model/Point.h>
#include <omero/model/PointI.h>
#include <omero/model/Polygon.h>
#include <omero/model/PolygonI.h>
#include <omero/model/Polyline.h>
#include <omero/model/PolylineI.h>
#include <omero/model/Project.h>
#include <omero/model/ProjectAnnotationLink.h>
#include <omero/model/ProjectAnnotationLinkI.h>
#include <omero/model/ProjectDatasetLink.h>
#include <omero/model/ProjectDatasetLinkI.h>
#include <omero/model/ProjectI.h>
#include <omero/model/Pulse.h>
#include <omero/model/PulseI.h>
#include <omero/model/QuantumDef.h>
#include <omero/model/QuantumDefI.h>
#include <omero/model/Reagent.h>
#include <omero/model/ReagentAnnotationLink.h>
#include <omero/model/ReagentAnnotationLinkI.h>
#include <omero/model/ReagentI.h>
#include <omero/model/Rect.h>
#include <omero/model/RectI.h>
#include <omero/model/RenderingDef.h>
#include <omero/model/RenderingDefI.h>
#include <omero/model/RenderingModel.h>
#include <omero/model/RenderingModelI.h>
#include <omero/model/ReverseIntensityContext.h>
#include <omero/model/ReverseIntensityContextI.h>
#include <omero/model/Roi.h>
#include <omero/model/RoiAnnotationLink.h>
#include <omero/model/RoiAnnotationLinkI.h>
#include <omero/model/RoiI.h>
#include <omero/model/Screen.h>
#include <omero/model/ScreenAnnotationLink.h>
#include <omero/model/ScreenAnnotationLinkI.h>
#include <omero/model/ScreenI.h>
#include <omero/model/ScreenPlateLink.h>
#include <omero/model/ScreenPlateLinkI.h>
#include <omero/model/ScriptJob.h>
#include <omero/model/ScriptJobI.h>
#include <omero/model/Session.h>
#include <omero/model/SessionAnnotationLink.h>
#include <omero/model/SessionAnnotationLinkI.h>
#include <omero/model/SessionI.h>
#include <omero/model/Shape.h>
#include <omero/model/ShapeI.h>
#include <omero/model/Share.h>
#include <omero/model/ShareI.h>
#include <omero/model/ShareMember.h>
#include <omero/model/ShareMemberI.h>
#include <omero/model/StageLabel.h>
#include <omero/model/StageLabelI.h>
#include <omero/model/StatsInfo.h>
#include <omero/model/StatsInfoI.h>
#include <omero/model/TagAnnotation.h>
#include <omero/model/TagAnnotationI.h>
#include <omero/model/TermAnnotation.h>
#include <omero/model/TermAnnotationI.h>
#include <omero/model/TextAnnotation.h>
#include <omero/model/TextAnnotationI.h>
#include <omero/model/Thumbnail.h>
#include <omero/model/ThumbnailGenerationJob.h>
#include <omero/model/ThumbnailGenerationJobI.h>
#include <omero/model/ThumbnailI.h>
#include <omero/model/TimestampAnnotation.h>
#include <omero/model/TimestampAnnotationI.h>
#include <omero/model/TransmittanceRange.h>
#include <omero/model/TransmittanceRangeI.h>
#include <omero/model/TypeAnnotation.h>
#include <omero/model/TypeAnnotationI.h>
#include <omero/model/UploadJob.h>
#include <omero/model/UploadJobI.h>
#include <omero/model/Well.h>
#include <omero/model/WellAnnotationLink.h>
#include <omero/model/WellAnnotationLinkI.h>
#include <omero/model/WellI.h>
#include <omero/model/WellReagentLink.h>
#include <omero/model/WellReagentLinkI.h>
#include <omero/model/WellSample.h>
#include <omero/model/WellSampleAnnotationLink.h>
#include <omero/model/WellSampleAnnotationLinkI.h>
#include <omero/model/WellSampleI.h>
#include <omero/model/XmlAnnotation.h>
#include <omero/model/XmlAnnotationI.h>
